import models.MapPoint;
import views.MainFrame;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import controllers.MapController;

public class App {
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        SwingUtilities.invokeLater(() -> {
            MapController controller = new MapController();
            controller.addPoint("n1", 42, 27);
            controller.addPoint("Parque Miraflores", 129, 75);
            controller.addPoint("n2", 69, 118);
            controller.addPoint("n3", 68, 219);
            controller.addPoint("n4", 139, 309);
            controller.addPoint("n5", 38, 282);
            controller.addPoint("n8", 85, 292);
            controller.addPoint("n6", 17, 362);
            controller.addPoint("n7", 65, 368);
            controller.addPoint("n9", 234, 420);
            controller.addPoint("n10", 223, 51);
            controller.addPoint("n11", 349, 45);
            controller.addPoint("n12", 383, 5);
            controller.addPoint("Av Turuhuayco", 525, 52);
            controller.addPoint("n13", 909, 181);
            controller.addPoint("n14", 484, 130);
            controller.addPoint("n16", 765, 131);
            controller.addPoint("n17", 842, 30);
            controller.addPoint("n15", 782, 249);
            controller.addPoint("n65", 559, 341);
            controller.addPoint("n18", 32, 438);
            controller.addPoint("n19", 105, 458);
            controller.addPoint("n20", 346, 420);
            controller.addPoint("n21", 579, 356);
            controller.addPoint("n22", 743, 291);
            controller.addPoint("n23", 948, 195);
            controller.addPoint("n24", 1237, 65);
            controller.addPoint("n25", 1381, 17);
            controller.addPoint("n26", 1290, 20);
            controller.addPoint("n27", 1022, 132);
            controller.addPoint("n28", 996, 107);
            controller.addPoint("n29", 1075, 13);
            controller.addPoint("n30", 1058, 234);
            controller.addPoint("n31", 1142, 259);
            controller.addPoint("n32", 1301, 314);
            controller.addPoint("n33", 1316, 137);
            controller.addPoint("n34", 1242, 127);
            controller.addPoint("n35", 1459, 382);
            controller.addPoint("Universidad Politecnica Salesiana", 1265, 484);
            controller.addPoint("n36", 1145, 557);
            controller.addPoint("n37", 1393, 718);
            controller.addPoint("n38", 1433, 221);
            controller.addPoint("n39", 969, 658);
            controller.addPoint("n40", 881, 704);
            controller.addPoint("n41", 802, 659);
            controller.addPoint("n42", 737, 616);
            controller.addPoint("n43", 691, 587);
            controller.addPoint("n44", 629, 648);
            controller.addPoint("n45", 557, 713);
            controller.addPoint("n46", 674, 674);
            controller.addPoint("n47", 734, 711);
            controller.addPoint("n48", 758, 521);
            controller.addPoint("n49", 791, 471);
            controller.addPoint("n50", 879, 403);
            controller.addPoint("n51", 930, 354);
            controller.addPoint("n52", 832, 285);
            controller.addPoint("n53", 686, 410);
            controller.addPoint("n54", 653, 429);
            controller.addPoint("n55", 519, 555);
            controller.addPoint("n56", 420, 494);
            controller.addPoint("n57", 444, 632);
            controller.addPoint("n58", 343, 724);
            controller.addPoint("n59", 421, 655);
            controller.addPoint("n60", 270, 588);
            controller.addPoint("n61", 175, 522);
            controller.addPoint("n63", 237, 606);
            controller.addPoint("n62", 46, 610);
            controller.addPoint("n64", 181, 710);
            controller.addPoint("n67", 514, 582);
            controller.addPoint("n66", 691, 479);
            
            conectar(controller, "n1", "Parque Miraflores");
            conectar(controller, "Parque Miraflores", "n1");
            conectar(controller, "Parque Miraflores", "n2");
            conectar(controller, "Parque Miraflores", "n10");
            conectar(controller, "n2", "Parque Miraflores");
            conectar(controller, "n2", "n3");
            conectar(controller, "n3", "n2");
            conectar(controller, "n3", "n4");
            conectar(controller, "n4", "n3");
            conectar(controller, "n4", "n8");
            conectar(controller, "n4", "n9");
            conectar(controller, "n5", "n8");
            conectar(controller, "n5", "n6");
            conectar(controller, "n8", "n4");
            conectar(controller, "n8", "n5");
            conectar(controller, "n8", "n7");
            conectar(controller, "n6", "n5");
            conectar(controller, "n6", "n7");
            conectar(controller, "n7", "n6");
            conectar(controller, "n7", "n8");
            conectar(controller, "n9", "n4");
            conectar(controller, "n9", "n65");
            conectar(controller, "n9", "n18");
            conectar(controller, "n10", "Parque Miraflores");
            conectar(controller, "n10", "n11");
            conectar(controller, "n11", "n10");
            conectar(controller, "n11", "n12");
            conectar(controller, "n12", "n11");
            conectar(controller, "n12", "Av Turuhuayco");
            conectar(controller, "Av Turuhuayco", "n12");
            conectar(controller, "Av Turuhuayco", "n14");
            conectar(controller, "Av Turuhuayco", "n16");
            conectar(controller, "n13", "n16");
            conectar(controller, "n13", "n15");
            conectar(controller, "n13", "n23");
            conectar(controller, "n14", "Av Turuhuayco");
            conectar(controller, "n14", "n15");
            conectar(controller, "n16", "Av Turuhuayco");
            conectar(controller, "n16", "n17");
            conectar(controller, "n16", "n13");
            conectar(controller, "n17", "n16");
            conectar(controller, "n15", "n14");
            conectar(controller, "n15", "n13");
            conectar(controller, "n15", "n65");
            conectar(controller, "n65", "n15");
            conectar(controller, "n65", "n9");
            conectar(controller, "n18", "n9");
            conectar(controller, "n18", "n19");
            conectar(controller, "n19", "n18");
            conectar(controller, "n19", "n20");
            conectar(controller, "n19", "n61");
            conectar(controller, "n20", "n19");
            conectar(controller, "n20", "n21");
            conectar(controller, "n20", "n56");
            conectar(controller, "n21", "n20");
            conectar(controller, "n21", "n22");
            conectar(controller, "n21", "n54");
            conectar(controller, "n22", "n21");
            conectar(controller, "n22", "n23");
            conectar(controller, "n23", "n22");
            conectar(controller, "n23", "n24");
            conectar(controller, "n23", "n28");
            conectar(controller, "n23", "n13");
            conectar(controller, "n23", "n30");
            conectar(controller, "n23", "n52");
            conectar(controller, "n24", "n23");
            conectar(controller, "n24", "n25");
            conectar(controller, "n24", "n34");
            conectar(controller, "n25", "n24");
            conectar(controller, "n25", "n26");
            conectar(controller, "n26", "n25");
            conectar(controller, "n26", "n27");
            conectar(controller, "n27", "n26");
            conectar(controller, "n27", "n28");
            conectar(controller, "n28", "n27");
            conectar(controller, "n28", "n29");
            conectar(controller, "n28", "n23");
            conectar(controller, "n29", "n28");
            conectar(controller, "n30", "n23");
            conectar(controller, "n30", "n31");
            conectar(controller, "n30", "n51");
            conectar(controller, "n31", "n30");
            conectar(controller, "n31", "n32");
            conectar(controller, "n31", "n33");
            conectar(controller, "n32", "n31");
            conectar(controller, "n32", "n35");
            conectar(controller, "n32", "n38");
            conectar(controller, "n33", "n38");
            conectar(controller, "n33", "n31");
            conectar(controller, "n33", "n34");
            conectar(controller, "n34", "n33");
            conectar(controller, "n34", "n24");
            conectar(controller, "n35", "n32");
            conectar(controller, "n35", "Universidad Politecnica Salesiana");
            conectar(controller, "Universidad Politecnica Salesiana", "n35");
            conectar(controller, "Universidad Politecnica Salesiana", "n36");
            conectar(controller, "n36", "Universidad Politecnica Salesiana");
            conectar(controller, "n36", "n37");
            conectar(controller, "n36", "n39");
            conectar(controller, "n37", "n36");
            conectar(controller, "n38", "n32");
            conectar(controller, "n38", "n33");
            conectar(controller, "n39", "n36");
            conectar(controller, "n39", "n40");
            conectar(controller, "n39", "n48");
            conectar(controller, "n40", "n39");
            conectar(controller, "n40", "n41");
            conectar(controller, "n41", "n40");
            conectar(controller, "n41", "n47");
            conectar(controller, "n41", "n42");
            conectar(controller, "n42", "n46");
            conectar(controller, "n42", "n41");
            conectar(controller, "n42", "n43");
            conectar(controller, "n43", "n42");
            conectar(controller, "n43", "n48");
            conectar(controller, "n43", "n44");
            conectar(controller, "n44", "n67");
            conectar(controller, "n44", "n45");
            conectar(controller, "n44", "n43");
            conectar(controller, "n44", "n46");
            conectar(controller, "n45", "n57");
            conectar(controller, "n45", "n44");
            conectar(controller, "n46", "n47");
            conectar(controller, "n46", "n42");
            conectar(controller, "n46", "n44");
            conectar(controller, "n47", "n41");
            conectar(controller, "n47", "n46");
            conectar(controller, "n48", "n43");
            conectar(controller, "n48", "n39");
            conectar(controller, "n48", "n49");
            conectar(controller, "n48", "n66");
            conectar(controller, "n49", "n48");
            conectar(controller, "n49", "n50");
            conectar(controller, "n49", "n53");
            conectar(controller, "n50", "n49");
            conectar(controller, "n50", "n51");
            conectar(controller, "n51", "n50");
            conectar(controller, "n51", "n30");
            conectar(controller, "n51", "n52");
            conectar(controller, "n52", "n51");
            conectar(controller, "n52", "n23");
            conectar(controller, "n52", "n53");
            conectar(controller, "n53", "n52");
            conectar(controller, "n53", "n49");
            conectar(controller, "n53", "n54");
            conectar(controller, "n54", "n53");
            conectar(controller, "n54", "n21");
            conectar(controller, "n54", "n55");
            conectar(controller, "n55", "n54");
            conectar(controller, "n55", "n67");
            conectar(controller, "n55", "n57");
            conectar(controller, "n55", "n56");
            conectar(controller, "n56", "n20");
            conectar(controller, "n56", "n55");
            conectar(controller, "n57", "n55");
            conectar(controller, "n57", "n59");
            conectar(controller, "n57", "n45");
            conectar(controller, "n58", "n59");
            conectar(controller, "n59", "n57");
            conectar(controller, "n59", "n58");
            conectar(controller, "n59", "n60");
            conectar(controller, "n60", "n59");
            conectar(controller, "n60", "n61");
            conectar(controller, "n60", "n63");
            conectar(controller, "n61", "n60");
            conectar(controller, "n61", "n19");
            conectar(controller, "n63", "n60");
            conectar(controller, "n63", "n64");
            conectar(controller, "n63", "n62");
            conectar(controller, "n62", "n63");
            conectar(controller, "n64", "n63");
            conectar(controller, "n67", "n55");
            conectar(controller, "n67", "n44");
            conectar(controller, "n66", "n48");

            MainFrame frame = new MainFrame(controller);
            frame.setVisible(true);
        });
    }

    private static void conectar(MapController controller, String id1, String id2) {
        models.MapPoint p1 = null;
        models.MapPoint p2 = null;
        
        for (structures.node.Node<models.MapPoint> node : controller.getGraph().getNodes()) {
            if (node.getValue().getId().equals(id1)) p1 = node.getValue();
            if (node.getValue().getId().equals(id2)) p2 = node.getValue();
        }
        
        if (p1 != null && p2 != null) {
            controller.addConnection(p1, p2, true);
        }
    }
}